name: build_windows
on: [workflow_dispatch]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        # - uses: microsoft/setup-msbuild@v2
        - uses: egor-tensin/setup-mingw@v2
        - run: (mingw64-make && ls src)